# Generated by Django 3.0.7 on 2020-08-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commands',
            options={'verbose_name': 'command', 'verbose_name_plural': 'command'},
        ),
        migrations.AlterModelOptions(
            name='emailsendlog',
            options={'ordering': ['-created_time'], 'verbose_name': 'EmailSendLog', 'verbose_name_plural': 'EmailSendLog'},
        ),
        migrations.AlterField(
            model_name='commands',
            name='command',
            field=models.CharField(max_length=2000, verbose_name='command'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='describe',
            field=models.CharField(max_length=300, verbose_name='Command description'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='last_mod_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Command title'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='content',
            field=models.TextField(verbose_name='content of email'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='emailto',
            field=models.CharField(max_length=300, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='send_result',
            field=models.BooleanField(default=False, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='emailsendlog',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='mail title'),
        ),
    ]
