# Generated by Django 3.0.7 on 2020-08-30 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Create source'),
        ),
    ]
