# Generated by Django 3.0.7 on 2020-08-30 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthconfig',
            options={'ordering': ['-created_time'], 'verbose_name': 'oauthuser', 'verbose_name_plural': 'oauthuser'},
        ),
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'ordering': ['-created_time'], 'verbose_name': 'oauthuser', 'verbose_name_plural': 'oauthuser'},
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='callback_url',
            field=models.CharField(default='http://www.baidu.com', max_length=200, verbose_name='Callback address'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='is_enable',
            field=models.BooleanField(default=True, verbose_name='Whether to show'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change the time'),
        ),
        migrations.AlterField(
            model_name='oauthconfig',
            name='type',
            field=models.CharField(choices=[('weibo', 'Weibo'), ('google', 'Google'), ('github', 'GitHub'), ('facebook', 'FaceBook'), ('qq', 'QQ')], default='a', max_length=10, verbose_name='Types of'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='oauthuser',
            name='last_mod_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Change the time'),
        ),
    ]
